Quiz 1: 맨 가장자리는 모두 0, 내부는 모두 1인 10by 10 행렬을 구하라

In [1]:
import numpy as np

In [2]:
array= np.zeros((10,10))
array[1:-1,1:-1]=1
array

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

Quiz 2 : 행렬 A, B에 대하여 ((A+B)×(−A/2))를 in place (without copy)로 계산하여라.

In [3]:
A = np.arange(10, dtype=np.float64)
B = np.linspace(11, 20, num=10)

C=np.add(A,B)
NA=np.negative(A)
D=np.divide(NA,2)
R=np.multiply(C,D)

R


array([  -0. ,   -6.5,  -15. ,  -25.5,  -38. ,  -52.5,  -69. ,  -87.5,
       -108. , -130.5])

Quiz 3:

3개의 배열이 주어졌을 때, 아래의 조건에 따라 새롭게 생성되는 배열을 구하시오
cond[i]가 true이면, xarr[i]를 선택
cond[i]가 false이면, yarr[i]를 선택


In [4]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])
answer_array=[x if c== True else y  for  x,y,c in zip(xarr,yarr,cond)]
answer_array

[1.1, 2.2, 1.3, 1.4, 2.5]

Quiz 4 : 크기가 11인 배열이 다음과 같이 주어졌을 때, 5번째 원소부터 9번째 원소까지를 음수로 바꾸어 보시오.

quiz4Arr = np.arange(11)

In [5]:
quiz4Arr = np.arange(11)
quiz4Arr[4:9] *= -1
quiz4Arr

array([ 0,  1,  2,  3, -4, -5, -6, -7, -8,  9, 10])

Quiz 5 : 난수생성기를 사용하여 크기가 0부터 9까지의 숫자로 구성된, 크기가 20인 배열을 생성하고, 배열의 최대값을 0으로 만들어라.

In [6]:
np.random.seed(43)
quiz5Arr = np.random.randint(0, 10, 20)
display(quiz5Arr)
display(np.argmax(quiz5Arr))
quiz5Arr[np.argmax(quiz5Arr)] = 0
display(quiz5Arr)

array([4, 0, 1, 5, 0, 3, 1, 2, 7, 0, 3, 2, 9, 1, 2, 2, 3, 5, 4, 4])

12

array([4, 0, 1, 5, 0, 3, 1, 2, 7, 0, 3, 2, 0, 1, 2, 2, 3, 5, 4, 4])