# broad casting **** important advanced
knn 가장 가까운 이웃 / 각 점에 대해서 하나의 점이 거리가 어떻게 되는 지/

In [1]:
#같은 크기의 배열의 연산
import numpy as np

a=np.array([0,1,2])
b=np.array([5,5,5])

a+b

array([5, 6, 7])

In [2]:
#1 by 3 배열과 scala의 합

a+5

array([5, 6, 7])

In [3]:
#3 by 3 배열과 1 by 3배열의 합
# 3 by 3 + 1 by 3 => 3 by 3

mat=np.ones((3,3))
display(mat)
display(a)

#1 차원 배열은 2 차원 배열의 형상을 맞추기 위해 두 번째 차원 까지 확장 또는 브로드캐스팅
# 그래서 a는 ([0,1,2],[0,1,2],[0,1,2])  이렇게 3차원으로 바뀜

display(mat+a)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

array([0, 1, 2])

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [4]:
#1 by 3배열과 3 by 1 배열의 합

a= np.arange(3)
b=np.arange(3)[:,np.newaxis]

display(a)
display(b)

# a= (0,1,2) b=(0),(1),(2) -> 브로드 캐스팅 -> 연산
#1 *3 +3*1 = 3*3 + 3*3 
#(0,1,2)(0,1,2)(0,1,2) + (0,0,0)(1,1,1)(2,2,2)=(0,1,2)(1,2,3)(2,3,4)

display(a+b)



array([0, 1, 2])

array([[0],
       [1],
       [2]])

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

# 2. Broad casting rule

Numpy의 브로드 캐스팅은 두 배열 사이의 상호 작용을 결정하기 위해
엄격한 규칙을 따른다 -> 상호 작용이라 하면 차원 수가 다른 배열 끼리 합을 구할 때, 차원수가 변경 되는 것?

1. 두 배열의 차원 수가 다르면 더 작은 수의 차원을 가진 배열 형상의 앞 쪽을
   1로 채운다.
2. 두 배열의 형상이 어떤 차원에서 일치하지 않는 다면, 해당 차원의 형상이 1인 배열을
   다른 형상의 차원과 일치하도록 형상을 늘린다.
3. 임의의 차원에서 크기가 일치하지 않고 1도 아니라면 오류가 발생한다.

example 01._element wise *1 때만 업데이트 해야함!(shape function)

In [5]:
mat = np.ones((2,3))
vec = np. arange(3)# 이거 차원이 1 by 3 아닌 가요? 차원과 형상은 다른 건가요? 형상이 뭐죠?

display(mat)
display(vec)

"""
1.각 배열의 형상
"""
print("==shape==")
print(mat.shape)
print(vec.shape) 
print("========")

"""
2. 규칙 1(1. 두 배열의 차원 수가 다르면 더 작은 수의 차원을 가진 배열 형상의 앞 쪽을
   1로 채운다.) 에 따라서 배열 vec이 더 작은 차원을 가지므로

mat.shape=(2,3)
vec.shape=(1,3)

3. 규칙 2(2. 두 배열의 형상이 어떤 차원에서 일치하지 않는 다면, 해당 차원의 형상이 1인 배열을
   다른 형상의 차원과 일치하도록 형상을 늘린다.)에 따라서 배열 vec이 다른 형상의 차원이므로
mat.shape=(2,3)
vec.shape=(2,3)
"""

display(mat +vec)


array([[1., 1., 1.],
       [1., 1., 1.]])

array([0, 1, 2])

==shape==
(2, 3)
(3,)


array([[1., 2., 3.],
       [1., 2., 3.]])

example 02. element wise\ ****1 때만 업데이트 해야함!(shape function)

In [6]:
vec1=np.arange(3).reshape((3,1))
vec2=np.arange(3)

display(vec1)
display(vec2)

"""
1.각 배열의 형상
(3,1)
(3,)
"""
print("==shape==")
print(vec1.shape)
print(vec2.shape) 
print("========")


"""
2. 규칙 1(1. 두 배열의 차원 수가 다르면 더 작은 수의 차원을 가진 배열 형상의 앞 쪽을
   1로 채운다.) 에 따라서 배열 vec이 더 작은 차원을 가지므로

mat.shape=(3,1)
vec.shape=(1,3)

3. 규칙 2(2. 두 배열의 형상이 어떤 차원에서 일치하지 않는 다면, 해당 차원의 형상이 1인 배열을
   다른 형상의 차원과 일치하도록 형상을 늘린다.)에 따라서 배열 vec이 다른 형상의 차원이므로
mat.shape=(3,1)
vec.shape=(3,3)
"""

display(vec1 +vec2)

array([[0],
       [1],
       [2]])

array([0, 1, 2])

==shape==
(3, 1)
(3,)


array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

example3. 

In [7]:
mat = np.ones((3,2))
vec= np.arange(3)

display(mat)
display(vec)

"""
1.각 배열의 형상
(3,2)
(3,)
"""
print("==shape==")
print(mat.shape)
print(vec.shape) 
print("========")


"""
2. 규칙 1(1. 두 배열의 차원 수가 다르면 더 작은 수의 차원을 가진 배열 형상의 앞 쪽을
   1로 채운다.) 에 따라서 배열 vec이 더 작은 차원을 가지므로

mat.shape=(3,2)
vec.shape=(1,3)

3. 규칙 2(2. 두 배열의 형상이 어떤 차원에서 일치하지 않는 다면, 해당 차원의 형상이 1인 배열을
   다른 형상의 차원과 일치하도록 형상을 늘린다.)에 따라서 배열 vec이 다른 형상의 차원이므로
mat.shape=(3,2)
vec.shape=(3,3)
"""

display(mat +vec)

# 브로드 캐스팅 결과, 벡터 형상이 일치 하지 않아 오류

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

array([0, 1, 2])

==shape==
(3, 2)
(3,)


ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

In [8]:
new_vec = vec.reshape (3,1)
display(new_vec)

print('Shape:', new_vec.shape)

"""
1.각 배열의 형상
-mat.shape=(3,2)
-new_vec.shape=(3,1)

2.규칙 1일 따라 채울 차원 없음
-mat.shape=(3,2)
-new_vec.shape=(3,1)

3.규칙 2에 따라
-mat.shape=(3,2)
-new_vec.shape=(3,2)

"""

display(mat + new_vec)

array([[0],
       [1],
       [2]])

Shape: (3, 1)


array([[1., 1.],
       [2., 2.],
       [3., 3.]])

# practical broadcasting

배열을 중앙 정렬 하기 : feature별(column)별 평균을 0으로 만들기 위해서 사용한다.

#굳이 왜요? 이걸 언제 쓰나요??


by feature 제로 평균 **중요 제로 평균의 의미는 평균이 제로가 되도록 점의 위치를 옮겨라! 제로 평균은 다 더하면 0이 되는 것 제로 평균을 구하는 방법은 열별 평균을 구해서 각 값을 평균으로 빼는 것

In [9]:
x=np.random.random((10,3))
# numpy.random.random is Return random floats in the half-open interval [0.0, 1.0).
#Results are from the “continuous uniform” distribution over the stated interval
#함수의 균등 연속 이란?"continuous uniform”

"""
넘파이 랜덤 랜덤 함수의 타입은?
type(x)
"""

# 첫번째 차원의 특성별 평균 값
x_mean =x.mean(axis=0) #vertical이 기본 값

#평균 값을 뻄으로써 x 배열을 중앙 정렬(브로드캐스팅 연산)\
x_cent=x-x_mean

display(x)
display(x_mean)
display(x_cent)
display(np.round(x_cent.sum(axis=0),10)#이게 이해가 안되요

SyntaxError: unexpected EOF while parsing (<ipython-input-9-22f899cd6583>, line 20)