In [ ]:
v= (2,0,3,9,0,1,0,-5,8,7,1,7)
w=(8,3,1,1,0,4,-1,0,1,1,11)

In [ ]:
vector_add=[v_i + w_i for v_i,w_i in zip(v,w)]

In [ ]:
vector_add

In [ ]:
vector_substract =[v_i - w_i for v_i,w_i in zip(v,w)]

In [ ]:
vector_substract

In [ ]:
scala_multiply=[2* v_i for v_i in v]

In [ ]:
scala_multiply

In [ ]:
dot = sum(v_i * w_i for v_i,w_i in zip(v,w))

In [ ]:
dot

In [ ]:
list(zip(v,w))

In [ ]:
import math

In [ ]:
math.sqrt(sum([(a*b)**2 for a,b in list(zip(v,w)) ]))

In [ ]:
d= sum(a*b for a,b in zip(v,w))

In [ ]:
d_1=math.sqrt(sum([a*a for a in v]))

In [ ]:
d_2=math.sqrt(sum([a*a for a in w]))

In [ ]:
c_s=d/(d_1*d_2)

In [ ]:
c_s


# Numpy


Dataset은 광범위한 원천으로부터 문서나 이미지, 음악, 수치 측정값 등 모든 것을 아우르는 매우 다양한 형식으로 들어올 수 있다. 이러한 다양성에도 불구하고 모든 데이터를 근본적으로 숫자 배열로 간주하는 것이 도움이 될 것이다.
데이터가 무엇이든 상관없이 그 데이터를 분석할 수 있게 만드는 첫 번째 단계는 데이터를 숫자 배열로 변환하는 것이다.
이러한 숫자 배열을 다루기 위해 파이선에서 사용할 수 있는 전문 도구에는 Numpy 패키지와 Pandas 패키지가 있다.
Numpy(Numerical Python)은 조밀한 데이터 버퍼에서 저장하고 처리하는 효과적인 인터페이스를 제공한다. 파이선에서 제공하는 list와 비슷하지만 배열의 규모가 커질수록 데이터 저장 및 처리에 훨씬 더 효율적이다

In [ ]:
a=['a',1,(2,3)]
a

넘파이와 파이선 리스트의 차이점
파이선 리스트는 자유형을 지원함 ( 리스트안에 리스트, 튜플 인티저 다 들어갈 수 있음)
그러나 자바나 씨는 인티저 리스트에 인티저 밖에 들어갈 수 없음
넘파이의 경우, 인티저 리스트에 인티저밖에 들어갈 수 밖에 없음!(넘파이가 더 빠름. 왜 타입의 정보가 필요 없으니까)
두개의 형타입이 완전히 같을때는  파이선 리스트가 더 빠르나, 다른 경우는 넘파이가 빠름


In [3]:
import numpy as np

# Python 정수

In [8]:
#python list
l=list(range(10))

In [13]:
l[0]

0

In [ ]:
l.shape

In [ ]:
np.reshape(a,(1,10))

In [ ]:
#0으로 채운 길이 10의 정수 배열 만들기
np.zeros(10,dtype=int)

In [ ]:
#
np.full((3,5),3.14)

In [ ]:
# 0에서 시작해 2씩 더해 20까지 채움
np..arrange(0,20,2)

In [ ]:
# 0과 1사이에 일정한 간격을 가진 다섯개의 값으로 채운 배열 만들기
np.linespace(0,1,5)

In [ ]:
#균등하게 분포된 3 바이 3 배열 만들기. 0과 1사이의 난수로 채움. 유니폼 분포에서 난수가 생성
np.random.random((3,3))

In [ ]:
#표준정규분포(평균=0,분산=1)의 난수로 채운 3 바이 3배열 만들기
np.random.normal(0,1(3,3))

In [ ]:
#0~9 구간의 임의의 정수로 채운 3바이3 배열 만들기/넘파이에서 랜덤 하게 뽑는 것은 다 유니폼 사용함
np.random.randint(0,10,(3,3))

# numpy 배열의 속성 지정

In [ ]:
import numpy as np
#np.random.seed(10)# 재현 가능성을 위한 시드값./ 시드를 해야 랜덤 값이 고정됨
#x1=np.random.randint(10,size=4)


In [ ]:
np.random.seed(10)

In [16]:
x1=np.random.randint(10,size=4)
x1

array([4, 1, 4, 3])

In [ ]:
x3= np.random.randint(10,size(2,3,4))

In [12]:
s_l=[str(i)for i in l]

In [ ]:
s_l

In [ ]:
s_l[0].isdigit()

In [ ]:
#dynamic typing
l_dy = [True, "2", 3.0, 4]
[type(item) for item in l_dy]

In [ ]:
np.array([1,23])

In [4]:
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
#NUMPY Ndarray(파이선 넘파이에서 사용하는 어레이의 형타입)

fl_arr =np.array ([3.14,4,2,3])
fl_arr

array([3.14, 4.  , 2.  , 3.  ])

In [7]:
[type(elem) for elem in fl_arr]

[numpy.float64, numpy.float64, numpy.float64, numpy.float64]

In [ ]:
str_arr=np.array(["wow",3.14,2,3])

명시적으로 결과 배열의 데이터 타입을 설정하려면 dtype키워드를 사용하면 된다.

In [ ]:
fl32_arr=np.array([1,2,3,4],)

In [ ]:
np.array([[2,3,4],[4,5,6],[6,7,8]])

In [ ]:
print "x3:",x3.ndim
print"x3:"".
print


# 2. 배열 인덱싱:단일 요소에 접근하기

In [ ]:
#데이터를 슬라이싱 하는 경우, 슬라이싱 한 데이터는 별도의 리스트를 만드는 것임( 별도의 메모리를 사용하는 것임)